# settings_cp.py
# *Summary:* Script to set up the cart-pole scenario
#
# Copyright (C) 2008-2013 by
# Marc Deisenroth, Andrew McHutchon, Joe Hall, and Carl Edward Rasmussen.
#
# Last modified: 2013-05-24
#
## High-Level Steps
# # Define state and important indices
# # Set up scenario
# # Set up the plant structure
# # Set up the policy structure
# # Set up the cost structure
# # Set up the GP dynamics model structure
# # Parameters for policy optimization
# # Plotting verbosity
# # Some array initializations

import numpy as np
from .dynamics_cp import dynamics_cp
from .loss_cp import loss_cp


# MATLAB-verified initial rollout data (rand('seed',1); randn('seed',1))
# Generated by export_cartpole_iter1.m
# Full augmented rollout: [x, v, dtheta, theta, sin(theta), cos(theta), u]
_ROLLOUT_XX = np.array([
    [-0.06432155, -0.13827009, -0.03068687, 0.17412924, 0.17325061, 0.98487777, -0.79032499],
    [-0.07604196, -0.16271256, -0.44591528, 0.12731497, 0.12697131, 0.99190639, -2.99209253],
    [-0.11564878, -0.57229112, 0.29964505, 0.13172178, 0.13134120, 0.99133722, -8.09908530],
    [-0.21594654, -1.67571100, 2.96380934, 0.31935876, 0.31395780, 0.94943694, -1.32657912],
    [-0.38600578, -1.56887601, 1.51379830, 0.55122081, 0.52372761, 0.85188579, 4.18470395],
    [-0.49340005, -0.77385882, -2.16696861, 0.50917030, 0.48745296, 0.87314925, -7.68063535],
    [-0.63147205, -1.64006160, -0.96768117, 0.35821515, 0.35060324, 0.93652409, -8.43830636],
    [-0.85031023, -2.70949504, 1.08366779, 0.34683900, 0.33992674, 0.94045192, -2.61494184],
    [-1.11702178, -2.85824605, 0.33835872, 0.42175619, 0.40936338, 0.91237143, -9.32743244],
    [-1.45970655, -3.91980389, 1.81132250, 0.54870824, 0.52158554, 0.85319900, -6.15699249],
    [-1.88486109, -4.40512220, 1.29106340, 0.71760138, 0.65757948, 0.75338518, -0.57280309],
    [-2.31198964, -4.18100963, -1.15839678, 0.71657565, 0.65680636, 0.75405928, -7.10154360],
    [-2.74435878, -4.83008653, -1.43168187, 0.56656436, 0.53673640, 0.84374999, 4.35671055],
    [-3.21282472, -3.83115618, -5.33486278, 0.23360771, 0.23148874, 0.97283758, 3.23428556],
    [-3.54725514, -3.35672303, -6.51392386, -0.40324127, -0.39240170, 0.91979395, -1.36259174],
    [-3.92936255, -3.97507359, -3.31427557, -0.89232344, -0.77853205, 0.62760485, -1.07930228],
    [-4.33557771, -4.27316388, -0.34344171, -1.06089622, -0.87279327, 0.48809006, 0.16663068],
    [-4.76578896, -4.40646964, 2.39248706, -0.97513109, -0.82777544, 0.56105955, 0.56175746],
    [-5.23142306, -4.63760068, 5.02784166, -0.59450189, -0.56009617, 0.82842759, 1.45756033],
    [-5.66852262, -4.68821590, 6.00103486, -0.01331051, -0.01331012, 0.99991142, -2.78355866],
    [-6.14780414, -4.72299026, 5.29806418, 0.58178057, 0.54951245, 0.83548553, -3.27045485],
    [-6.62036552, -4.66624626, 3.03263278, 0.99310281, 0.83772443, 0.54609319, -6.53467470],
    [-7.09666269, -5.09148434, 0.95433304, 1.21575955, 0.93763370, 0.34762485, -8.27763035],
    [-7.66989237, -5.77202971, -1.09372403, 1.21798508, 0.93840503, 0.34553726, -2.13327260],
    [-8.23425912, -5.70135860, -3.81563390, 0.96079823, 0.81964911, 0.57286590, 6.08735774],
    [-8.75512714, -4.25610456, -9.02277557, 0.32309324, 0.31750126, 0.94825785, -9.77838625],
    [-9.23598857, -5.73551960, -4.45911291, -0.40524411, -0.39424311, 0.91900618, -5.33773565],
    [-9.85631137, -6.67436582, -0.55986575, -0.63285052, -0.59144566, 0.80634486, 8.67701172],
    [-10.48738047, -5.70324133, -0.96813399, -0.72551398, -0.66352007, 0.74815848, -5.46404957],
    [-11.08847830, -6.57473491, 2.93446014, -0.61777983, -0.57922678, 0.81516645, 5.71893940],
    [-11.71983075, -5.96613554, 2.63476286, -0.32921573, -0.32330098, 0.94629619, -1.78542346],
    [-12.31586723, -6.27783451, 4.04979121, 0.00295028, 0.00295027, 0.99999565, -7.61214450],
    [-13.01430717, -7.05626899, 5.59719793, 0.52991447, 0.50545954, 0.86285031, 2.68740690],
    [-13.65894737, -6.25893732, 1.86085711, 0.89895509, 0.78267696, 0.62242813, 7.24776372],
    [-14.22646852, -5.14268219, -2.56919811, 0.86486918, 0.76101040, 0.64873967, -6.83512681],
    [-14.76752285, -5.61400523, -3.40211841, 0.54479493, 0.51824272, 0.85523358, 2.02370156],
    [-15.29606965, -4.92337346, -6.19564927, 0.05288898, 0.05286433, 0.99860170, -7.64785375],
    [-15.83318925, -6.19432109, -2.01440482, -0.36736820, -0.35916048, 0.93327582, 2.52196719],
    [-16.45984986, -5.98061444, -1.29678550, -0.53514314, -0.50996418, 0.86019564, 6.70249349],
    [-17.01780863, -5.23722501, -1.41937844, -0.67655155, -0.62610787, 0.77973645, 8.80813418],
])

# Target states (next state): [x_n, v_n, dtheta_n, theta_n]
_ROLLOUT_YY = np.array([
    [-0.07604196, -0.16271256, -0.44591528, 0.12731497],
    [-0.11564878, -0.57229112, 0.29964505, 0.13172178],
    [-0.21594654, -1.67571100, 2.96380934, 0.31935876],
    [-0.38600578, -1.56887601, 1.51379830, 0.55122081],
    [-0.49340005, -0.77385882, -2.16696861, 0.50917030],
    [-0.63147205, -1.64006160, -0.96768117, 0.35821515],
    [-0.85031023, -2.70949504, 1.08366779, 0.34683900],
    [-1.11702178, -2.85824605, 0.33835872, 0.42175619],
    [-1.45970655, -3.91980389, 1.81132250, 0.54870824],
    [-1.88486109, -4.40512220, 1.29106340, 0.71760138],
    [-2.31198964, -4.18100963, -1.15839678, 0.71657565],
    [-2.74435878, -4.83008653, -1.43168187, 0.56656436],
    [-3.21282472, -3.83115618, -5.33486278, 0.23360771],
    [-3.54725514, -3.35672303, -6.51392386, -0.40324127],
    [-3.92936255, -3.97507359, -3.31427557, -0.89232344],
    [-4.33557771, -4.27316388, -0.34344171, -1.06089622],
    [-4.76578896, -4.40646964, 2.39248706, -0.97513109],
    [-5.23142306, -4.63760068, 5.02784166, -0.59450189],
    [-5.66852262, -4.68821590, 6.00103486, -0.01331051],
    [-6.14780414, -4.72299026, 5.29806418, 0.58178057],
    [-6.62036552, -4.66624626, 3.03263278, 0.99310281],
    [-7.09666269, -5.09148434, 0.95433304, 1.21575955],
    [-7.66989237, -5.77202971, -1.09372403, 1.21798508],
    [-8.23425912, -5.70135860, -3.81563390, 0.96079823],
    [-8.75512714, -4.25610456, -9.02277557, 0.32309324],
    [-9.23598857, -5.73551960, -4.45911291, -0.40524411],
    [-9.85631137, -6.67436582, -0.55986575, -0.63285052],
    [-10.48738047, -5.70324133, -0.96813399, -0.72551398],
    [-11.08847830, -6.57473491, 2.93446014, -0.61777983],
    [-11.71983075, -5.96613554, 2.63476286, -0.32921573],
    [-12.31586723, -6.27783451, 4.04979121, 0.00295028],
    [-13.01430717, -7.05626899, 5.59719793, 0.52991447],
    [-13.65894737, -6.25893732, 1.86085711, 0.89895509],
    [-14.22646852, -5.14268219, -2.56919811, 0.86486918],
    [-14.76752285, -5.61400523, -3.40211841, 0.54479493],
    [-15.29606965, -4.92337346, -6.19564927, 0.05288898],
    [-15.83318925, -6.19432109, -2.01440482, -0.36736820],
    [-16.45984986, -5.98061444, -1.29678550, -0.53514314],
    [-17.01780863, -5.23722501, -1.41937844, -0.67655155],
    [-17.48311384, -4.33686508, -1.41532569, -0.83185500],
])


def get_matlab_rollout_data():
    """Return MATLAB-verified initial rollout data for deterministic GP training."""
    return _ROLLOUT_XX, _ROLLOUT_YY


def define_settings():
    # Code

    # 1. Define state and important indices

    # 1a. Full state representation (including all augmentations)
    #
    #  0  x          cart position
    #  1  v          cart velocity
    #  2  dtheta     angular velocity
    #  3  theta      angle of the pendulum
    #  4  sin(theta) complex representation ...
    #  5  cos(theta) of theta
    #  6  u          force applied to cart
    #

    # 1b. Important indices (0-based)
    # odei  indicies for the ode solver
    # augi  indicies for variables augmented to the ode variables
    # dyno  indicies for the output from the dynamics model and indicies to loss
    # angi  indicies for variables treated as angles (using sin/cos representation)
    # dyni  indicies for inputs to the dynamics model
    # poli  indicies for the inputs to the policy
    # difi  indicies for training targets that are differences (rather than values)

    odei = np.array([0, 1, 2, 3])        # varibles for the ode solver
    augi = np.array([], dtype=int)       # variables to be augmented
    dyno = np.array([0, 1, 2, 3])        # variables to be predicted (and known to loss)
    angi = np.array([3])                 # angle variables
    dyni = np.array([0, 1, 2, 4, 5])     # variables that serve as inputs to the dynamics GP
    poli = np.array([0, 1, 2, 4, 5])     # variables that serve as inputs to the policy
    difi = np.array([0, 1, 2, 3])        # variables that are learned via differences

    # 2. Set up the scenario
    dt = 0.10                            # [s] sampling time
    T = 4.0                              # [s] initial prediction horizon time
    H = int(np.ceil(T / dt))             # prediction steps (optimization horizon)
    mu0 = np.array([0.0, 0.0, 0.0, 0.0])  # initial state mean
    S0 = np.diag([0.1, 0.1, 0.1, 0.1])**2  # initial state covariance
    N = 15   # number controller optimizations
    J = 1    # initial J trajectories of length H
    K = 1    # no. of initial states for which we optimize
    nc = 10  # number of controller basis functions

    # 3. Plant structure
    plant = {
        'dynamics': dynamics_cp,
        'noise': np.diag(np.ones(4) * 0.01**2),
        'dt': dt,
        'ctrl': None,                     # zoh placeholder; implemented in rollout/simulate
        'odei': odei,
        'augi': augi,
        'angi': angi,
        'poli': poli,
        'dyno': dyno,
        'dyni': dyni,
        'difi': difi,
        'prop': None,                     # placeholder; propagated from base module
    }

    # 4. Policy structure
    # Create augmented state distribution for policy initialization
    from pilco_python.util.gTrig import gTrig
    mm, ss, cc = gTrig(mu0, S0, plant['angi'], compute_derivatives=False)
    mm_full = np.concatenate([mu0, mm])
    cc_full = S0 @ cc
    ss_full = np.vstack([
        np.hstack([S0, cc_full]),
        np.hstack([cc_full.T, ss]),
    ])

    mm_poli = mm_full[poli]
    ss_poli = ss_full[np.ix_(poli, poli)]

    # MATLAB-verified deterministic initial policy parameters
    # (from rand('seed',1); randn('seed',1) in settings_cp.m)
    # These match the gaussian(mm(poli), ss(poli,poli), nc)' and 0.1*randn(nc,1)
    # that MATLAB produces, ensuring identical controller initialization.
    policy = {
        'fcn': None,                      # placeholder; conCat(@congp, @gSat, ...)
        'maxU': np.array([10.0]),
        'p': {
            'inputs': np.array([
                [ 0.09794489, -0.02656113, -0.05483727, -0.00957886,  0.98529831],
                [-0.07283710,  0.18860020, -0.29413859,  0.09751413,  0.98662753],
                [-0.04379819,  0.13664593, -0.08726523,  0.00888823,  0.99675494],
                [ 0.04069927,  0.06480664, -0.01644799,  0.08074739,  0.99788556],
                [-0.12900886,  0.09637103,  0.06525533, -0.04087942,  0.98256176],
                [ 0.04394770,  0.04951815,  0.06846166, -0.03938784,  0.99535736],
                [-0.03721677,  0.02569628,  0.08107261, -0.03384447,  0.98573476],
                [-0.21091725,  0.03065567, -0.07888152, -0.05011983,  1.00594067],
                [ 0.03207998, -0.01926759,  0.15578507,  0.00563501,  0.98639806],
                [ 0.00651551, -0.10947729, -0.10694118,  0.02154947,  0.98957636],
            ]),
            'targets': np.array([
                [-0.08308569],
                [ 0.09619756],
                [-0.09459684],
                [ 0.09196610],
                [-0.11389537],
                [ 0.05934399],
                [-0.06337483],
                [-0.09260176],
                [ 0.12280029],
                [ 0.04550096],
            ]),
            'hyp': np.log([1, 1, 1, 0.7, 0.7, 1, 0.01]),
        }
    }

    # 5. Set up the cost structure
    cost = {
        'fcn': loss_cp,
        'gamma': 1,
        'p': 0.5,
        'width': 0.25,
        'expl': 0.0,
        'angle': np.array([3]),  # plant.angi
        'target': np.array([0.0, 0.0, 0.0, np.pi]),
    }

    # 6. Dynamics model structure
    dynmodel = {
        'fcn': None,               # placeholder; gp1d
        'train': None,             # placeholder; train
        'induce': np.zeros((300, 0, 1)),
    }
    trainOpt = [300, 500]          # max. number of line searches for GP training

    # 7. Parameters for policy optimization
    opt = {
        'length': 150,
        'MFEPLS': 30,
        'verbosity': 1,
    }

    # 8. Plotting verbosity
    plotting = {'verbosity': 1}    # 0: no plots, 1: some plots, 2: all plots

    # 9. Some initializations
    x = np.zeros((0, len(dyno)))
    y = np.zeros((0, len(dyno)))
    fantasy_mean = [None] * N
    fantasy_std = [None] * N
    realCost = [None] * N
    M = [None] * N
    Sigma = [None] * N

    settings = {
        'odei': odei, 'augi': augi, 'dyno': dyno, 'angi': angi,
        'dyni': dyni, 'poli': poli, 'difi': difi,
        'dt': dt, 'T': T, 'H': H, 'mu0': mu0, 'S0': S0,
        'N': N, 'J': J, 'K': K, 'nc': nc,
        'plant': plant, 'policy': policy, 'cost': cost,
        'dynmodel': dynmodel, 'trainOpt': trainOpt, 'opt': opt,
        'plotting': plotting,
        'x': x, 'y': y,
        'fantasy_mean': fantasy_mean, 'fantasy_std': fantasy_std,
        'realCost': realCost, 'M': M, 'Sigma': Sigma,
        'mu0Sim': mu0[dyno],
        'S0Sim': S0[np.ix_(dyno, dyno)],
    }

    return settings
